server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
        - id: restaurants-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/restaurants/**
        - id: products-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/products/**
        - id: orders-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/orders/**
        - id: delivery-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/deliveries/**

jwt:
  Secret-Key: 37c1e0f2c3e93f11ab066045c43c8d17
